apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: 'true'
spec:
  rules:
    - host: z-commerce.zeabix.com
      http:
        paths:
          - path: /api/payments/?(.*)
            backend:
              service:
                name: payments-srv
              service:
                port: 3000
          - path: /api/users/?(.*)
            backend:
              service:
                name: auth-srv
              service:
                port: 3000
          - path: /api/tickets/?(.*)
            backend:
              service:
                name: tickets-srv
              service:
                port: 3000
          - path: /api/orders/?(.*)
            backend:
              service: 
                name: orders-srv
              service:
                port: 3000
          - path: /?(.*)
            backend:
              service
                name: client-srv
              service
                port: 3000
