# kaitest1
name: workflow-feature-client

on:
  push:
    branches:
      - feature-*

jobs:
  Preparation:
    runs-on: ubuntu-latest
    name: Environment Preparation
    steps:
      - name:

  build:
    uses: ./.github/workflows/build-master.yaml
    with: 
      app_name: ticketing-client
      app_dir:  client
      env_flag: DEV
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
      docker_tag: ${{needs.build.outputs.docker_tag}}
      env_flag:   DEV

    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      creds:  '${{ secrets.AZURE_CREDENTIALS_DEV }}'
      cluster-name: ${{ secrets.CLUSTER_NAME_DEV }}
      resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP_DEV }}

