# kaitest1
name: build-master

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_dir:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true


jobs:
  build:
    name: build-${{github.ref}}
    if: "!contains(github.ref, 'master')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag env for docker tag
        run: |
          if [[ ${github.ref} == *"feature"* ]]
          then
            echo "TAG_VERSION=${{ github.sha }}" >> $GITHUB_ENV

          elif [[ ${github.ref} == *"tag"* ]]   
          then   
            echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            echo ${GITHUB_REF#refs/*/}            
            echo ${GITHUB_REF#refs/*/} > release_candidate_tag.txt 
            cat release_candidate_tag.txt
          fi
 
      - name: Build Docker Image with proper tag. 
        run:  cd ${{inputs.app_dir}} && docker build -t zeabixdockerrepo/${{inputs.app_name}}:${TAG_VERSION} .
      - name: Docker login
        run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
      - name: Docker push
        run:  docker push zeabixdockerrepo/${{inputs.app_name}}:$TAG_VERSION

      - name: Upload git tag version for release candidate
        if: "contains(github.ref, 'tags')"
        uses: actions/upload-artifact@v3
        with:
          name: release_candidate_tag
          path: release_candidate_tag.txt 