# kaitest1
name: build-master

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_dir:
        required: true
        type: string
      env_flag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
    outputs:
      docker_tag:
        description: "docker_tag for further deployment stage"
        value: ${{jobs.build.outputs.docker_tag }}
      env_flag:
        description: "env_flag"
        value: ${{ jobs.build.outputs.env_flag }}

    
jobs:
  Preparation:
    runs-on: ubuntu-latest
    steps:
      - name: Hello World!
        id: test1
        run: |
          echo "hello world"

  build:
    name: ${{github.ref}}
    if: "!contains(github.ref, 'master')"
    runs-on: ubuntu-latest
    outputs:
      docker_tag: ${{ steps.set_docker_tag.outputs.docker_tag }}
      env_flag: ${{ steps.set_docker_tag.outputs.env_flag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set tag env for docker tag
        id: set_docker_tag
        run: |
          echo  ${{inputs.env_flag}}
          if [[ ${{inputs.env_flag}} == "DEV" ]] 
          then
            echo "TAG_VERSION=${{ github.sha }}" >> $GITHUB_ENV
            export TAG_VERSION_TEMP=${{ github.sha }}
          
          elif [[ ${{inputs.env_flag}} == "RELEASE" ]]   
          then   
            echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
            export TAG_VERSION_TEMP=${GITHUB_REF#refs/*/}
            echo ${GITHUB_REF#refs/*/}            
            echo ${GITHUB_REF#refs/*/} > release_candidate_tag.txt 
            cat release_candidate_tag.txt
          fi
          echo "::set-output name=docker_tag::$TAG_VERSION_TEMP"
          echo "::set-output name=env_flag::${{inputs.env_flag}}"
         
          echo "$TAG_VERSION"
          export kai=kai
          echo "$kai"
          echo "$TAG_VERSION_TEMP"
          echo "$TAG_VERSION_TEMP"

          

      - name: Build Docker Image with proper tag. 
        run:  | 
          cd ${{inputs.app_dir}} && docker build -t zeabixdockerrepo/${{inputs.app_name}}:${TAG_VERSION} .
          echo "$TAG_VERSION"

      - name: Docker Registry login
        run:  docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        
        env:
          DOCKER_USERNAME: ${{ secrets.docker_username }}
          DOCKER_PASSWORD: ${{ secrets.docker_password }}
      - name: Docker push
        run:  |
          docker push zeabixdockerrepo/${{inputs.app_name}}:$TAG_VERSION
          echo "$TAG_VERSION"

      - name: Upload git tag version for release candidate
        if: "contains(github.ref, 'tags')"
        uses: actions/upload-artifact@v3
        with:
          name: release_candidate_tag
          path: release_candidate_tag.txt 

