# kaitest1
name: deploy-master

on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
      app_dir:
        required: true
        type: string
      docker_tag:
        required: true
        type: string
      env_flag:
        required: true
        type: string
    secrets:
      docker_username:
        required: true
      docker_password:
        required: true
      aks_cred:
        required: true
      aks_cluster_name:
        required: true
      aks_rg_name:
        required: true
jobs:

  deploy:
    name: ${{github.ref}}
    runs-on: ubuntu-latest 
    steps:
      - uses: actions/checkout@v2 
      - run: |
          echo ${{inputs.app_name}}
          echo ${{inputs.app_dir}}
          echo ${{inputs.docker_tag}}
          echo ${{inputs.env_flag}}
      