# kaitest1
name: deploy-ticketing-client

on:
  push:
    branches:
      - master
      - feature-*
#   paths:
#     - 'client/**'
    tags: 
      - 'v*.*.*'
env:
  ENV_FLAG: NOT_DEFINED
    

jobs:
  Evironment_Preperation:
    runs-on: ubuntu-latest 
    steps:
    - name: Detect Environment
      run: |
        if [[ ${{github.ref}} == *"feature"* ]]
          then
            echo "ENV_FLAG=DEV" >> $GITHUB_ENV
          
        elif [[ ${{github.ref}} == *"tag"* ]]   
          then   
           echo "ENV_FLAG=QA" >> $GITHUB_ENV

        elif [[ ${{github.ref}} == *"master"* ]]  
          then   
           echo "ENV_FLAG=PROD" >> $GITHUB_ENV 
        fi

        
        echo "$ENV_FLAG"
        ENV_FLAG=new_one
        echo "$ENV_FLAG"
    
  build:
    uses: ./.github/workflows/build-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
      ENV_FLAG: 
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
      docker_tag: ${{needs.build.outputs.docker_tag}}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

