# kaitest1
name: deploy-ticketing-client

on:
  push:
    branches:
      - master
      - feature-*
#   paths:
#     - 'client/**'
    tags: 
      - 'v*.*.*'
env:
  ENV_FLAG: NOT_DEFINED
    

jobs:
  Evironment_Preperation:
    runs-on: ubuntu-latest 
    steps:
    - run: |
        echo "$ENV_FLAG"
        ENV_FLAG=new_one
        echo "$ENV_FLAG"
    
  build:
    uses: ./.github/workflows/build-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
      docker_tag: ${{needs.build.outputs.docker_tag}}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

