# kaitest1
name: deploy-ticketing-client

on:
  push:
    branches:
      - master
      - feature-*
#   paths:
#     - 'client/**'
    tags: 
      - 'v*.*.*'

jobs:
  build:
    uses: ./.github/workflows/build-master.yaml
    with:
      app_name: ticketing-client
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

