# kaitest1
name: deploy-ticketing-client

on:
  push:
    branches:
      - master
      - feature-*
#   paths:
#     - 'client/**'
    tags: 
      - 'v*.*.*'

jobs:
  build:
    if: "!contains(github.ref, 'master')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set tag env for release candidate
        if: "contains(github.ref, 'tags')"
        run: |
          echo "TAG_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV 
          echo $TAG_VERSION > release_candidate_tag.txt 

      - name: Set tag env for feature branch
        if: "contains(github.ref, 'feature')"
        run: echo "TAG_VERSION=${{ github.sha }}" >> $GITHUB_ENV
 
      - run: cd client && docker build -t zeabixdockerrepo/ticketing-client:$TAG_VERSION .
      - run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      - run: docker push zeabixdockerrepo/ticketing-client:$TAG_VERSION

      - name: Upload git tag version for release candidate
        if: "contains(github.ref, 'tags')"
        uses: actions/upload-artifact@v3
        with:
          name: release_candidate_tag
          path: release_candidate_tag.txt

  deploy:
    runs-on: ubuntu-latest 
    needs: build   
    steps:
      - uses: actions/checkout@v2 

      - name: Feature branch - use SHA as docker tag from github.sha and set kubeconfig for dev cluster
        if: "contains(github.ref, 'feature')" 
        env:
          AZURE_CREDENTIALS_TEMP: ${{ secrets.AZURE_CREDENTIALS_DEV }}
          CLUSTER_NAME_TEMP: ${{ secrets.CLUSTER_NAME_DEV }}
          CLUSTER_RESOURCE_GROUP_TEMP: ${{ secrets.CLUSTER_RESOURCE_GROUP_DEV }}
        run: |
          echo "TAG_VERSION_TEMP=${{ github.sha }}" >> $GITHUB_ENV
          echo $AZURE_CREDENTIALS_TEMP
        #  echo "AZURE_CREDENTIALS_TEMP=${AZURE_CREDENTIALS_TEMP}" >> $GITHUB_ENV
        #  echo "CLUSTER_NAME_TEMP=${CLUSTER_NAME_TEMP}" >> $GITHUB_ENV
        #  echo "CLUSTER_RESOURCE_GROUP_TEMP=${CLUSTER_RESOURCE_GROUP_TEMP}" >> $GITHUB_ENV
        #  echo "::set-env name=AZURE_CREDENTIALS_TEMP::$AZURE_CREDENTIALS_TEMP"
        #  echo "::set-env name=CLUSTER_NAME_TEMP::$CLUSTER_NAME_TEMP"
        #  echo "::set-env name=CLUSTER_RESOURCE_GROUP_TEMP::$CLUSTER_RESOURCE_GROUP_TEMP"
        #  echo "AZURE_CREDENTIALS_TEMP=${{ secrets.AZURE_CREDENTIALS_DEV }}" >> $GITHUB_ENV
        #  echo "CLUSTER_NAME_TEMP=${{ secrets.CLUSTER_NAME_DEV }}" >> $GITHUB_ENV
        #  echo "CLUSTER_RESOURCE_GROUP_TEMP=${{ secrets.CLUSTER_RESOURCE_GROUP_DEV }}" >> $GITHUB_ENV


      - name: Release candidate - use git tag as docker tag from github.ref and set kubeconfig for QA cluster
        if: "contains(github.ref, 'tags')"
        run: |
          echo "TAG_VERSION_TEMP=${{ github.sha }}" >> $GITHUB_ENV
          echo "AZURE_CREDENTIALS_TEMP=${{ secrets.AZURE_CREDENTIALS }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME_TEMP=${{ secrets.CLUSTER_NAME }}" >> $GITHUB_ENV
          echo "CLUSTER_RESOURCE_GROUP_TEMP=${{ secrets.CLUSTER_RESOURCE_GROUP }}" >> $GITHUB_ENV

      - name: Production - download git tag saved in artifact
        if: "contains(github.ref, 'master')" 
        uses: actions/download-artifact@v3
        with:
          name: release_candidate_tag
        
      - name: Production - use git tag as docker tag from downloaded artifact and set kubeconfig for Prod cluster
        if: "contains(github.ref, 'master')"
        run: |
          TAG_VERSION_TEMP=$(release_candidate_tag.txt)
          echo "TAG_VERSION_TEMP" >> $GITHUB_ENV
          echo "AZURE_CREDENTIALS_TEMP=${{ secrets.AZURE_CREDENTIALS }}" >> $GITHUB_ENV
          echo "CLUSTER_NAME_TEMP=${{ secrets.CLUSTER_NAME }}" >> $GITHUB_ENV
          echo "CLUSTER_RESOURCE_GROUP_TEMP=${{ secrets.CLUSTER_RESOURCE_GROUP }}" >> $GITHUB_ENV

      - name: envsubst-action        
        uses: danielr1996/envsubst-action@1.1.0
        env:
            TAG_VERSION: '${{env.TAG_VERSION_TEMP}}'
        with:
          input: client/deployment/client-depl.yaml
          output: client/deployment/client-depl-go.yaml
          
      - uses: azure/aks-set-context@v1
        with:
          creds: '${{ env.AZURE_CREDENTIALS_TEMP }}'
          cluster-name: ${{ env.CLUSTER_NAME_TEMP }}
          resource-group: ${{ env.CLUSTER_RESOURCE_GROUP_DEV }}  

      - run: kubectl apply -f client/deployment/client-depl-go.yaml
    
          
          
          
