# kaitest1
name: DEV_ticketing-client_client

on:
  push:
    branches:
      - feature-*
env:
  app_name: ticketing-client

jobs:

  build:
    uses: ./.github/workflows/build-master.yaml
    with: 
      workflow_name: ${{github.workflow}}
    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}

  deploy:
    needs: build
    uses: ./.github/workflows/deploy-master.yaml
    with:
      app_name: ticketing-client
      app_dir: client
      docker_tag: ${{needs.build.outputs.docker_tag}}
      env_flag:   DEV

    secrets:
      docker_username: ${{ secrets.DOCKER_USERNAME }}
      docker_password: ${{ secrets.DOCKER_PASSWORD }}
      creds:  '${{ secrets.AZURE_CREDENTIALS_DEV }}'
      cluster-name: ${{ secrets.CLUSTER_NAME_DEV }}
      resource-group: ${{ secrets.CLUSTER_RESOURCE_GROUP_DEV }}

